version: '3'
services:
  api:
    image: sessionapi
    container_name: "session-api"
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
  mongodb:
    image: "mongo:4.0.6"
    container_name: "mongodb"
    ports:
      - "27017:27017"

